"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/bintang.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Bintang(props) {
  const { nodes, materials } = useGLTF("/bintang.glb");
  return (
    <group
      {...props}
      dispose={null}
      rotation={[0, -Math.PI / 2.05, 0]}
      position={[0.5, -3, -0.5]}
    >
      <mesh
        geometry={nodes["T#1_001"].geometry}
        material={materials.PaletteMaterial001}
        position={[-7.347, 3.972, -0.458]}
        rotation={[1.833, 0, -Math.PI / 2]}
        scale={[0.028, 0.044, 0.028]}
      />
      <mesh
        geometry={nodes.petalo.geometry}
        material={materials.Material_0}
        position={[-5.487, 0.686, 0.015]}
        rotation={[0.141, -1.248, -0.466]}
      />
      <mesh
        geometry={nodes.Cake.geometry}
        material={materials.cake}
        position={[-3.515, 2.64, 0.053]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.054}
      />
      <mesh
        geometry={nodes.Sphere005.geometry}
        material={materials.straw}
        position={[-3.515, 2.64, 0.053]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.054}
      />
      <instancedMesh
        args={[nodes.Mesh_0.geometry, materials.Material_0, 8]}
        instanceMatrix={nodes.Mesh_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_13.geometry, materials.Material_0, 86]}
        instanceMatrix={nodes.Mesh_13.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_120.geometry, materials.Material_0, 78]}
        instanceMatrix={nodes.Mesh_120.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_122.geometry, materials.Material_0, 87]}
        instanceMatrix={nodes.Mesh_122.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_123.geometry, materials.Material_0, 82]}
        instanceMatrix={nodes.Mesh_123.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_124.geometry, materials.Material_0, 86]}
        instanceMatrix={nodes.Mesh_124.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_125.geometry, materials.Material_0, 94]}
        instanceMatrix={nodes.Mesh_125.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_126.geometry, materials.Material_0, 92]}
        instanceMatrix={nodes.Mesh_126.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_127.geometry, materials.Material_0, 80]}
        instanceMatrix={nodes.Mesh_127.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_128.geometry, materials.Material_0, 82]}
        instanceMatrix={nodes.Mesh_128.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_118.geometry, materials.Material_0, 80]}
        instanceMatrix={nodes.Mesh_118.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_119.geometry, materials.Material_0, 80]}
        instanceMatrix={nodes.Mesh_119.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_117.geometry, materials.Material_0, 82]}
        instanceMatrix={nodes.Mesh_117.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_129.geometry, materials.Material_0, 38]}
        instanceMatrix={nodes.Mesh_129.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_131.geometry, materials.Material_0, 42]}
        instanceMatrix={nodes.Mesh_131.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_132.geometry, materials.Material_0, 40]}
        instanceMatrix={nodes.Mesh_132.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_130.geometry, materials.Material_0, 42]}
        instanceMatrix={nodes.Mesh_130.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_137.geometry, materials.Material_0, 17]}
        instanceMatrix={nodes.Mesh_137.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_139.geometry, materials.Material_0, 17]}
        instanceMatrix={nodes.Mesh_139.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_140.geometry, materials.Material_0, 17]}
        instanceMatrix={nodes.Mesh_140.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh_138.geometry, materials.Material_0, 17]}
        instanceMatrix={nodes.Mesh_138.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_1.geometry, materials["Material.002"], 3]}
        instanceMatrix={nodes.Object_1.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_16.geometry, materials["Material.002"], 11]}
        instanceMatrix={nodes.Object_16.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_2.geometry, materials["Material.002"], 3]}
        instanceMatrix={nodes.Object_2.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh001.geometry, materials["Material #3"], 15]}
        instanceMatrix={nodes.Mesh001.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh018.geometry, materials.cream, 17]}
        instanceMatrix={nodes.Mesh018.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh037.geometry, materials.egg, 17]}
        instanceMatrix={nodes.Mesh037.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh053.geometry, materials.PaletteMaterial001, 2]}
        instanceMatrix={nodes.Mesh053.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh054.geometry, materials.PaletteMaterial001, 2]}
        instanceMatrix={nodes.Mesh054.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh055.geometry, materials.PaletteMaterial001, 2]}
        instanceMatrix={nodes.Mesh055.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh061.geometry, materials.PaletteMaterial001, 2]}
        instanceMatrix={nodes.Mesh061.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh067.geometry, materials.PaletteMaterial001, 6]}
        instanceMatrix={nodes.Mesh067.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Mesh068.geometry, materials.PaletteMaterial001, 6]}
        instanceMatrix={nodes.Mesh068.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/bintang.glb");
