/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/envelope.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/envelope.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box001.geometry} material={materials.wire_028089177} rotation={[Math.PI / 2, 0, 0]} scale={0.004} />
      <mesh geometry={nodes.Box002.geometry} material={materials.wire_028089177} rotation={[Math.PI / 2, 0, 0]} scale={0.004} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.wire_088199225} rotation={[Math.PI / 2, 0, 0]} scale={0.004} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.wire_088199225} rotation={[Math.PI / 2, 0, 0]} scale={0.004} />
    </group>
  )
}

useGLTF.preload('/envelope.glb')
