/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/gift_box.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gift_box.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.04}>
        <mesh geometry={nodes['11564_Gift_Box_v1_l2_1'].geometry} material={materials['11564_gift_box']} />
        <mesh geometry={nodes['11564_Gift_Box_v1_l2_2'].geometry} material={materials['11564_gift_box_bow']} />
      </group>
    </group>
  )
}

useGLTF.preload('/gift_box.glb')
