/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 iphone.glb 
Author: utqau (https://sketchfab.com/utqau)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/iphone-15-pro-lowpoly-5a549e3d0f164a6b9c133bc894d4d49f
Title: iPhone 15 Pro Lowpoly
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Iphone(props) {
  const { nodes, materials } = useGLTF("/iphone.glb");
  return (
    <group {...props} dispose={null} rotation={[-Math.PI / 2.05, 0, 0]}>
      <group scale={0.01}>
        <group scale={0.01}>
          <mesh
            geometry={nodes.Circle_Camera_0.geometry}
            material={materials.Camera}
            position={[-727.462, 10125.382, 1219.446]}
            scale={[1734, 1734, 100]}
          />
          <mesh
            geometry={nodes.Circle_001_Camera_0.geometry}
            material={materials.Camera}
            position={[-4215.888, 8199.426, 1119.446]}
            scale={[1652.417, 1665.782, 100]}
          />
          <mesh
            geometry={nodes.Circle_002_Lidar_0.geometry}
            material={materials.Lidar}
            position={[-734.907, 7375.176, 1119.45]}
            scale={[642, 653, 100]}
          />
          <mesh
            geometry={nodes.Circle_003_Camera_0.geometry}
            material={materials.Camera}
            position={[-4244.635, 12038.203, 1119.446]}
            scale={[1639, 1654, 100]}
          />
          <mesh
            geometry={nodes.Circle_005_Lidar_0.geometry}
            material={materials.Lidar}
            position={[416.375, 8101.804, 1119.446]}
            scale={[161, 157, 100]}
          />
          <mesh
            geometry={nodes.Circle_006_Glass_0.geometry}
            material={materials.Glass}
            position={[-761.378, 10190.274, 1631.074]}
            scale={[1600, 1600, 100]}
          />
          <mesh
            geometry={nodes.Circle_007_Glass_001_0.geometry}
            material={materials.Glass_001}
            position={[-732.435, 12797.552, 1114.67]}
            scale={[600, 600, 100]}
          />
          <mesh
            geometry={nodes.Circle_008_Glass_002_0.geometry}
            material={materials.Glass_002}
            position={[-4245.566, 12051.292, 1560.482]}
            scale={[1600, 1600, 100]}
          />
          <mesh
            geometry={nodes.Circle_009_Glass_003_0.geometry}
            material={materials.Glass_003}
            position={[-4274.853, 8255.414, 1569.182]}
            scale={[1500, 1500, 100]}
          />
          <mesh
            geometry={nodes.Circle_010_Camera_001_0.geometry}
            material={materials.Camera_001}
            position={[-734.99, 12799.491, 1261.039]}
            scale={[700, 700, 100]}
          />
          <mesh
            geometry={nodes.Cube_NaturalTitanium__0.geometry}
            material={materials.NaturalTitanium}
            rotation={[-1.57, 0, 0]}
            scale={[7147.727, 820, 14842.021]}
          />
          <mesh
            geometry={nodes.Cube_001_NaturalTitanium__0.geometry}
            material={materials.NaturalTitanium}
            position={[-2475.089, 10127.876, 959.604]}
            rotation={[-1.57, 0, 0]}
            scale={[4136, 200, 4257.07]}
          />
          <mesh
            geometry={nodes.Cube_002_Buttons_0.geometry}
            material={materials.Buttons}
            position={[7097.914, 3029.791, 0]}
            rotation={[-1.57, 0, 0]}
            scale={[100, 300, 1208]}
          />
          <mesh
            geometry={nodes.Cube_003_Buttons_0.geometry}
            material={materials.Buttons}
            position={[7097.914, 5909.264, 0]}
            rotation={[-1.57, 0, 0]}
            scale={[100, 300, 1208]}
          />
          <mesh
            geometry={nodes.Cube_004_Buttons_0.geometry}
            material={materials.Buttons}
            position={[7097.914, 8626.558, 0]}
            rotation={[-1.57, 0, 0]}
            scale={[100, 300, 674]}
          />
          <mesh
            geometry={nodes.Cube_006_Buttons_0.geometry}
            material={materials.Buttons}
            position={[-7167.385, 3974.08, 0]}
            rotation={[-1.57, 0, 0]}
            scale={[100, 300, 1849]}
          />
          <mesh
            geometry={nodes.Cube_008_NaturalTitanium__0.geometry}
            material={materials.NaturalTitanium}
            position={[182.712, -14309.476, 0]}
            rotation={[-1.57, 0, 0]}
            scale={[700, 150, 400]}
          />
          <mesh
            geometry={nodes.Cube_010_Camera_001_0.geometry}
            material={materials.Camera_001}
            position={[70, 13437.063, -738.099]}
            rotation={[-1.57, 0, 0]}
            scale={[2196.188, 100, 700]}
          />
          <mesh
            geometry={nodes.Cylinder_010_Camera_0.geometry}
            material={materials.Camera}
            position={[2477.211, -14719.941, 0]}
            rotation={[-1.57, 0, 0]}
            scale={[200, 200, 50]}
          />
          <mesh
            geometry={nodes.Cylinder_011_Camera_001_0.geometry}
            material={materials.Camera_001}
            position={[2951.912, -14719.941, 0]}
            rotation={[-1.57, 0, 0]}
            scale={[200, 200, 50]}
          />
          <mesh
            geometry={nodes.Cylinder_012_Camera_002_0.geometry}
            material={materials.Camera_002}
            position={[3452.985, -14719.941, 0]}
            rotation={[-1.57, 0, 0]}
            scale={[200, 200, 50]}
          />
          <mesh
            geometry={nodes.Cylinder_013_Camera_003_0.geometry}
            material={materials.Camera_003}
            position={[-2183.095, -14719.941, 0]}
            rotation={[-1.57, 0, 0]}
            scale={[200, 200, 50]}
          />
          <mesh
            geometry={nodes.Cylinder_014_Camera_004_0.geometry}
            material={materials.Camera_004}
            position={[-2633.308, -14719.941, 0]}
            rotation={[-1.57, 0, 0]}
            scale={[200, 200, 50]}
          />
          <mesh
            geometry={nodes.Cylinder_015_Camera_005_0.geometry}
            material={materials.Camera_005}
            position={[-3087.288, -14719.941, 0]}
            rotation={[-1.57, 0, 0]}
            scale={[200, 200, 50]}
          />
          <mesh
            geometry={nodes.Cylinder_016_Camera_006_0.geometry}
            material={materials.Camera_006}
            position={[-3548.802, -14719.941, 0]}
            rotation={[-1.57, 0, 0]}
            scale={[200, 200, 50]}
          />
          <mesh
            geometry={nodes.Cylinder_017_Camera_007_0.geometry}
            material={materials.Camera_007}
            position={[-4025.387, -14719.941, 0]}
            rotation={[-1.57, 0, 0]}
            scale={[200, 200, 50]}
          />
          <mesh
            geometry={nodes.Cylinder_018_Gray_0.geometry}
            material={materials.Gray}
            position={[1463.709, -14719.941, 0]}
            rotation={[-1.57, 0, 0]}
            scale={[200, 200, 50]}
          />
          <mesh
            geometry={nodes.Cylinder_019_Gray_0.geometry}
            material={materials.Gray}
            position={[-1146.875, -14719.941, 0]}
            rotation={[-1.57, 0, 0]}
            scale={[200, 200, 50]}
          />
          <mesh
            geometry={nodes.Plane_Glass_0.geometry}
            material={materials.Glass}
            position={[-133.824, -260.914, 741.112]}
            scale={[1061.108, 911.781, 100]}
          />
          <mesh
            geometry={nodes.Plane_001_Glass_0.geometry}
            material={materials.Glass}
            position={[365.535, 1752.393, 741.112]}
            rotation={[0, 0, 0.873]}
            scale={[420.466, 157.504, 100]}
          />
          <mesh
            geometry={nodes.Plane_002_Plastic_0.geometry}
            material={materials.Plastic}
            position={[-2484.423, 10216.61, 734.212]}
            scale={[3900, 3900, 100]}
          />
          <mesh
            geometry={nodes.Plane_003_Glass_0.geometry}
            material={materials.Glass}
            position={[-5.124, 0, -722.526]}
            rotation={[Math.PI, 0, 0]}
            scale={[6951.283, 14551.104, 100]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/iphone.glb");
