"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/laras.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Laras(props) {
  const { nodes, materials } = useGLTF("/laras.glb");
  return (
    <group {...props} position={[-4, -4, -10]} dispose={null}>
      <group position={[0.435, 0, 5.359]} scale={0.101}>
        <group
          position={[29.394, -8.023, 23.258]}
          rotation={[0, Math.PI / 4, 0]}
        >
          <group
            position={[77.638, 8.023, -41.006]}
            rotation={[-Math.PI, 0.585, -Math.PI]}
          >
            <mesh
              geometry={nodes.instance_1.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1001.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1002.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1003.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1004.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1005.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_2.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2001.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2002.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2003.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2004.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2005.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2006.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_3.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3001.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3002.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3003.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3004.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3005.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3006.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3007.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_4.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4001.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4002.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4003.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4004.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4005.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4006.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4007.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4008.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4009.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_5.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5001.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5002.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5003.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5004.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5005.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5006.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_6.geometry}
              material={materials.__Color_008_2}
              position={[2.695, 10.635, -2.821]}
            />
            <mesh
              geometry={nodes.instance_7.geometry}
              material={materials.__Color_008_2}
              position={[2.503, 16.472, -2.529]}
            />
          </group>
          <group position={[41.006, 8.023, 3.178]} rotation={[0, 0.986, 0]}>
            <mesh
              geometry={nodes.instance_1006.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1007.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1008.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1009.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1010.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1011.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_2007.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2008.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2009.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2010.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2011.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2012.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2013.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_3008.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3009.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3010.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3011.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3012.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3013.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3014.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3015.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_4010.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4011.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4012.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4013.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4014.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4015.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4016.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4017.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4018.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4019.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_5007.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5008.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5009.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5010.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5011.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5012.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5013.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_6001.geometry}
              material={materials.__Color_008_2}
              position={[2.695, 10.635, -2.821]}
            />
            <mesh
              geometry={nodes.instance_7001.geometry}
              material={materials.__Color_008_2}
              position={[2.503, 16.472, -2.529]}
            />
          </group>
          <group position={[-3.178, 8.023, -33.454]} rotation={[0, -0.585, 0]}>
            <mesh
              geometry={nodes.instance_1012.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1013.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1014.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1015.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1016.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1017.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_2014.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2015.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2016.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2017.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2018.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2019.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2020.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_3016.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3017.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3018.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3019.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3020.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3021.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3022.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3023.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_4020.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4021.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4022.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4023.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4024.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4025.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4026.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4027.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4028.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4029.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_5014.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5015.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5016.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5017.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5018.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5019.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5020.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_6002.geometry}
              material={materials.__Color_008_2}
              position={[2.695, 10.635, -2.821]}
            />
            <mesh
              geometry={nodes.instance_7002.geometry}
              material={materials.__Color_008_2}
              position={[2.503, 16.472, -2.529]}
            />
          </group>
          <group
            position={[33.454, 8.023, -77.638]}
            rotation={[Math.PI, -0.986, Math.PI]}
          >
            <mesh
              geometry={nodes.instance_1018.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1019.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1020.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1021.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1022.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_1023.geometry}
              material={materials.__Color_008_2}
              position={[5.48, 0, 0]}
            />
            <mesh
              geometry={nodes.instance_2021.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2022.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2023.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2024.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2025.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2026.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_2027.geometry}
              material={materials.__Color_008_2}
              position={[17.275, 0, -5.176]}
            />
            <mesh
              geometry={nodes.instance_3024.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3025.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3026.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3027.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3028.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3029.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3030.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_3031.geometry}
              material={materials.__Color_008_2}
              position={[8.009, 0, -17.342]}
            />
            <mesh
              geometry={nodes.instance_4030.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4031.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4032.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4033.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4034.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4035.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4036.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4037.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4038.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_4039.geometry}
              material={materials.__Color_008_2}
              position={[0.287, 17.706, -1.102]}
            />
            <mesh
              geometry={nodes.instance_5021.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5022.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5023.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5024.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5025.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5026.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_5027.geometry}
              material={materials.__Color_008_2}
              position={[1.894, -0.082, -8.454]}
              rotation={[1.577, -0.039, -1.409]}
            />
            <mesh
              geometry={nodes.instance_6003.geometry}
              material={materials.__Color_008_2}
              position={[2.695, 10.635, -2.821]}
            />
            <mesh
              geometry={nodes.instance_7003.geometry}
              material={materials.__Color_008_2}
              position={[2.503, 16.472, -2.529]}
            />
          </group>
          <mesh
            geometry={nodes.group_0.geometry}
            material={materials.czary}
            position={[25.534, 8.063, -25.513]}
          >
            <mesh
              geometry={nodes.instance_8.geometry}
              material={materials.collon}
              position={[5.668, 0, -1.696]}
            >
              <mesh
                geometry={nodes.instance_10.geometry}
                material={materials.collon}
                position={[4.144, -0.622, -7.778]}
                rotation={[Math.PI, -Math.PI / 3, Math.PI]}
              />
              <mesh
                geometry={nodes.instance_11.geometry}
                material={materials.collon}
                position={[9.166, -0.622, -9.552]}
              />
              <mesh
                geometry={nodes.instance_9.geometry}
                material={materials.collon}
                position={[5.119, -0.622, -13.014]}
                rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
              />
            </mesh>
            <mesh
              geometry={nodes.instance_8001.geometry}
              material={materials.collon}
              position={[5.668, 0, -1.696]}
            />
            <mesh
              geometry={nodes.instance_8002.geometry}
              material={materials.__Color_008_2}
              position={[5.668, 0, -1.696]}
            />
            <mesh
              geometry={nodes.instance_8003.geometry}
              material={materials.__Color_008_2}
              position={[5.668, 0, -1.696]}
            />
            <mesh
              geometry={nodes.instance_8004.geometry}
              material={materials.__Color_008_2}
              position={[5.668, 0, -1.696]}
            />
            <mesh
              geometry={nodes.instance_8005.geometry}
              material={materials.__Color_008_2}
              position={[5.668, 0, -1.696]}
            />
            <mesh
              geometry={nodes.instance_8006.geometry}
              material={materials.__Color_008_2}
              position={[5.668, 0, -1.696]}
            />
            <mesh
              geometry={nodes.instance_8007.geometry}
              material={materials.__Color_008_2}
              position={[5.668, 0, -1.696]}
            />
          </mesh>
          <mesh
            geometry={nodes.group_0001.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0002.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0003.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0004.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0005.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0006.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0007.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0008.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0009.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0010.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0011.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0012.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0013.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0014.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0015.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0016.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0017.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0018.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0019.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0020.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0021.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0022.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0023.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0024.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0025.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0026.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0027.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0028.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0029.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0030.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0031.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0032.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0033.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0034.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0035.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0036.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0037.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0038.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0039.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0040.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0041.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0042.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0043.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0044.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0045.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0046.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0047.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0048.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0049.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0050.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0051.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0052.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0053.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0054.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0055.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0056.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0057.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0058.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0059.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0060.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0061.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0062.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0063.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0064.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0065.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0066.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0067.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0068.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0069.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0070.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0071.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0072.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0073.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0074.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0075.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0076.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0077.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0078.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0079.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0080.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0081.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0082.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0083.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0084.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0085.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0086.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0087.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0088.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0089.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0090.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0091.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0092.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0093.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0094.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0095.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0096.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0097.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0098.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0099.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0100.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0101.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0102.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0103.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0104.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0105.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0106.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0107.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0108.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0109.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0110.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0111.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0112.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0113.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0114.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0115.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0116.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0117.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0118.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0119.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0120.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0121.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0122.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0123.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0124.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0125.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0126.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0127.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0128.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0129.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0130.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0131.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0132.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0133.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0134.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0135.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0136.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0137.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0138.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0139.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0140.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0141.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0142.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0143.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0144.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0145.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0146.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0147.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0148.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0149.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0150.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0151.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0152.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0153.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0154.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0155.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0156.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0157.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0158.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
          <mesh
            geometry={nodes.group_0159.geometry}
            material={materials.__Color_008_2}
            position={[25.534, 8.063, -25.513]}
          />
        </group>
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.jujuba001_1.geometry}
          material={materials.initialShadingGroup}
        />
        <mesh
          geometry={nodes.jujuba001_2.geometry}
          material={materials.blinn1SG}
        />
        <mesh
          geometry={nodes.jujuba001_3.geometry}
          material={materials.lambert2SG}
        />
      </group>
      <group position={[0.275, 0, -3.875]} rotation={[Math.PI / 2, 0, -0.641]}>
        <mesh
          geometry={nodes.Balon001_Balon020_1.geometry}
          material={materials.Pomarańczowy}
        />
        <mesh
          geometry={nodes.Balon001_Balon020_2.geometry}
          material={materials.Pomarańczowy}
        />
        <mesh
          geometry={nodes.Balon001_Balon020_3.geometry}
          material={materials.czary}
        />
        <mesh
          geometry={nodes.Balon001_Balon020_4.geometry}
          material={materials.NIEBIESKI}
        />
      </group>
      <group position={[7.539, 0, -3.875]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Balon001_Balon001_1.geometry}
          material={materials.NIEBIESKI}
        />
        <mesh
          geometry={nodes.Balon001_Balon001_2.geometry}
          material={materials.Pomarańczowy}
        />
        <mesh
          geometry={nodes.Balon001_Balon001_3.geometry}
          material={materials.czary}
        />
        <mesh
          geometry={nodes.Balon001_Balon001_4.geometry}
          material={materials.NIEBIESKI}
        />
      </group>
      <group position={[7.539, 0, -7.925]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Balon001_Balon002_1.geometry}
          material={materials.NIEBIESKI}
        />
        <mesh
          geometry={nodes.Balon001_Balon002_2.geometry}
          material={materials.Pomarańczowy}
        />
        <mesh
          geometry={nodes.Balon001_Balon002_3.geometry}
          material={materials.czary}
        />
        <mesh
          geometry={nodes.Balon001_Balon002_4.geometry}
          material={materials.NIEBIESKI}
        />
      </group>
      <group position={[10.194, 0, -7.925]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Balon001_Balon003_1.geometry}
          material={materials.NIEBIESKI}
        />
        <mesh
          geometry={nodes.Balon001_Balon003_2.geometry}
          material={materials.Pomarańczowy}
        />
        <mesh
          geometry={nodes.Balon001_Balon003_3.geometry}
          material={materials.czary}
        />
        <mesh
          geometry={nodes.Balon001_Balon003_4.geometry}
          material={materials.NIEBIESKI}
        />
      </group>
      <group position={[10.194, 0, -4.109]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Balon001_Balon004_1.geometry}
          material={materials.NIEBIESKI}
        />
        <mesh
          geometry={nodes.Balon001_Balon004_2.geometry}
          material={materials.Pomarańczowy}
        />
        <mesh
          geometry={nodes.Balon001_Balon004_3.geometry}
          material={materials.czary}
        />
        <mesh
          geometry={nodes.Balon001_Balon004_4.geometry}
          material={materials.NIEBIESKI}
        />
      </group>
      <group position={[-4.889, 0, -2.702]} rotation={[Math.PI / 2, 0, -1.342]}>
        <mesh
          geometry={nodes.Balon001_Balon005_1.geometry}
          material={materials.NIEBIESKI}
        />
        <mesh
          geometry={nodes.Balon001_Balon005_2.geometry}
          material={materials.Pomarańczowy}
        />
        <mesh
          geometry={nodes.Balon001_Balon005_3.geometry}
          material={materials.czary}
        />
        <mesh
          geometry={nodes.Balon001_Balon005_4.geometry}
          material={materials.NIEBIESKI}
        />
      </group>
      <group position={[-7.67, 0, -3.875]} rotation={[Math.PI / 2, 0, -0.641]}>
        <mesh
          geometry={nodes.Balon001_Balon006_1.geometry}
          material={materials.NIEBIESKI}
        />
        <mesh
          geometry={nodes.Balon001_Balon006_2.geometry}
          material={materials.Pomarańczowy}
        />
        <mesh
          geometry={nodes.Balon001_Balon006_3.geometry}
          material={materials.czary}
        />
        <mesh
          geometry={nodes.Balon001_Balon006_4.geometry}
          material={materials.NIEBIESKI}
        />
      </group>
      <mesh
        geometry={nodes.cake.geometry}
        material={materials["cake.001"]}
        position={[3.406, 2.683, 2.268]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <group
        position={[4.419, 2.793, 3.052]}
        rotation={[2.125, 0.324, 0.452]}
        scale={[0.037, 0.013, 0.035]}
      >
        <mesh
          geometry={nodes.Cylinder081.geometry}
          material={materials.Makaron03}
        />
        <mesh
          geometry={nodes.Cylinder081_1.geometry}
          material={materials["White.001"]}
        />
        <mesh
          geometry={nodes.Cylinder081_2.geometry}
          material={materials.Makaron1}
        />
        <mesh
          geometry={nodes.Cylinder081_3.geometry}
          material={materials.Makaron01}
        />
        <mesh
          geometry={nodes.Cylinder081_4.geometry}
          material={materials.Makaron2}
        />
        <mesh
          geometry={nodes.Cylinder081_5.geometry}
          material={materials.Makaron02}
        />
        <mesh
          geometry={nodes.Cylinder081_6.geometry}
          material={materials.Makaron3}
        />
        <mesh
          geometry={nodes.Cylinder081_7.geometry}
          material={materials.Makaron4}
        />
        <mesh
          geometry={nodes.Cylinder081_8.geometry}
          material={materials.Makaron04}
        />
        <mesh
          geometry={nodes.Cylinder081_9.geometry}
          material={materials.Makaron5}
        />
        <mesh
          geometry={nodes.Cylinder081_10.geometry}
          material={materials.Makaron05}
        />
        <mesh
          geometry={nodes.Cylinder081_11.geometry}
          material={materials.Makaron6}
        />
        <mesh
          geometry={nodes.Cylinder081_12.geometry}
          material={materials.Makaron06}
        />
        <mesh
          geometry={nodes.Cylinder081_13.geometry}
          material={materials.Makaron7}
        />
        <mesh
          geometry={nodes.Cylinder081_14.geometry}
          material={materials.Makaron07}
        />
        <mesh
          geometry={nodes.Cylinder081_15.geometry}
          material={materials.Makaron8}
        />
        <mesh
          geometry={nodes.Cylinder081_16.geometry}
          material={materials.Makaron08}
        />
        <mesh
          geometry={nodes.Cylinder081_17.geometry}
          material={materials.Makaron9}
        />
        <mesh
          geometry={nodes.Cylinder081_18.geometry}
          material={materials.Makaron09}
        />
        <mesh
          geometry={nodes.Cylinder081_19.geometry}
          material={materials["candy sauce.001"]}
        />
      </group>
      <mesh
        geometry={nodes["Y#1_001"].geometry}
        material={materials.Material3}
        position={[7.828, 5.562, -5.642]}
        rotation={[Math.PI / 2, 0.304, 0]}
        scale={[0.072, 0.082, 0.06]}
      />
      <mesh
        geometry={nodes["A#1_001"].geometry}
        material={materials.Material3}
        position={[7.079, 5.46, -5.638]}
        rotation={[Math.PI / 2, 0.262, 0]}
        scale={[0.078, 0.082, 0.064]}
      />
      <mesh
        geometry={nodes["H#2_001"].geometry}
        material={materials.Material3}
        position={[5.979, 5.339, -5.638]}
        rotation={[Math.PI / 2, 0.262, 0]}
        scale={[0.06, 0.082, 0.054]}
      />
      <mesh
        geometry={nodes["T#1_001"].geometry}
        material={materials.Material3}
        position={[5.445, 5.26, -5.642]}
        rotation={[Math.PI / 2, 0.262, 0]}
        scale={[0.067, 0.082, 0.055]}
      />
      <mesh
        geometry={nodes["R#1_001"].geometry}
        material={materials.Material3}
        position={[4.707, 5.224, -5.642]}
        rotation={[Math.PI / 2, 0.098, 0]}
        scale={[0.074, 0.082, 0.059]}
      />
      <mesh
        geometry={nodes["I#1_001"].geometry}
        material={materials.Material3}
        position={[4.271, 5.229, -5.642]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.066, 0.082, 0.056]}
      />
      <mesh
        geometry={nodes["B#1_001"].geometry}
        material={materials.Material3}
        position={[3.542, 5.147, -5.642]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.083, 0.082, 0.066]}
      />
      <mesh
        geometry={nodes.Y_001.geometry}
        material={materials.Material3}
        position={[2.507, 5.208, -5.642]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.076, 0.082, 0.06]}
      />
      <mesh
        geometry={nodes["P#1_001"].geometry}
        material={materials.Material3}
        position={[1.884, 5.262, -5.642]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.073, 0.082, 0.058]}
      />
      <mesh
        geometry={nodes.P_001.geometry}
        material={materials.Material3}
        position={[1.215, 5.374, -5.642]}
        rotation={[Math.PI / 2, -0.157, 0]}
        scale={[0.073, 0.082, 0.059]}
      />
      <mesh
        geometry={nodes.A_001.geometry}
        material={materials.Material3}
        position={[0.493, 5.525, -5.642]}
        rotation={[Math.PI / 2, -0.216, 0]}
        scale={[0.076, 0.082, 0.062]}
      />
      <mesh
        geometry={nodes["H#1_001"].geometry}
        material={materials.Material3}
        position={[-0.229, 5.674, -5.642]}
        rotation={[Math.PI / 2, -0.229, 0]}
        scale={[0.071, 0.082, 0.058]}
      />
      <mesh
        geometry={nodes.D_001.geometry}
        material={materials.Material3}
        position={[6.568, 5.383, -5.642]}
        rotation={[Math.PI / 2, 0.262, 0]}
        scale={[0.072, 0.082, 0.059]}
      />
      <mesh
        geometry={nodes.Layer0_001.geometry}
        material={materials.Material4}
        position={[3.944, 5.734, -5.642]}
        scale={[0.104, 0.082, 0.082]}
      />
    </group>
  );
}

useGLTF.preload("/laras.glb");
